dist_url: https://dist.ipfs.io
ipfs_version: v0.4.19
ipfs_arch: amd64
ipfs_home: /home/ipfs
ipfs_storage_max: 10G
ipfs_bloom_filter_size: 1048576 # 1MB
ipfs_api_listen: /ip4/127.0.0.1/tcp/5001
ipfs_fd_max: 4092

ipfs_cluster_secret: "use `od  -vN 32 -An -tx1 /dev/urandom | tr -d ' \n' ; echo` to generate this"
ipfs_cluster_arch: amd64
ipfs_cluster_version: v0.10.0


ipfs_cluster_state_sync_interval: 1m
ipfs_cluster_ipfs_sync_interval: 2m
ipfs_cluster_repl_factor_min: 2
ipfs_cluster_repl_factor_max: 3
ipfs_cluster_monitor_ping_interval: 45s
ipfs_cluster_peer_watch_interval: 5s
ipfs_cluster_disable_repinning: false

ipfs_cluster_raft_init_peerset: []
ipfs_cluster_raft_wait_for_leader_timeout: 25s
ipfs_cluster_raft_commit_retries: 2
ipfs_cluster_raft_commit_retry_delay: 300ms
ipfs_cluster_raft_backups_rotate: 6
ipfs_cluster_raft_heartbeat_timeout: 1500ms
ipfs_cluster_raft_election_timeout: 1500ms
ipfs_cluster_raft_commit_timeout: 100ms
ipfs_cluster_raft_snapshot_interval: 2m
ipfs_cluster_raft_snapshot_threshold: 4096
ipfs_cluster_raft_leader_lease_timeout: 800ms

ipfs_cluster_ipfsproxy_listen_multiaddress: "/ip4/127.0.0.1/tcp/9095"

ipfs_cluster_api_http_listen_multiaddress: "/ip4/127.0.0.1/tcp/9094"
ipfs_cluster_api_read_timeout: 30s
ipfs_cluster_api_read_header_timeout: 5s
ipfs_cluster_api_write_timeout: 1m
ipfs_cluster_api_idle_timeout: 2m

ipfs_cluster_ipfsconn_pin_method: refs
ipfs_cluster_ipfsconn_ipfs_request_timeout: 5m0s
ipfs_cluster_ipfsconn_pin_timeout: 24h0m0s
ipfs_cluster_ipfsconn_unpin_timeout: 3h0m0s

ipfs_cluster_pintracker_concurrent_pins: 10

ipfs_cluster_informer_disk_metric_ttl: 5m
ipfs_cluster_informer_disk_metric_type: "freespace"
