dist_url: https://dist.ipfs.io
ipfs_version: v0.4.19
ipfs_arch: amd64
ipfs_home: /home/ipfs
ipfs_storage_max: 10G
ipfs_bloom_filter_size: 1048576 # 1MB
ipfs_api_listen: /ip4/127.0.0.1/tcp/5001
ipfs_fd_max: 4092
ipfs_use_badger: false
ipfs_discovery: false
ipfs_disk_sync: true
ipfs_routing: dht
ipfs_disable_bandthwidth_metrics: false
ipfs_reprovider_strategy: all